### ISSUE TITLE
Missing code actions

### ISSUE THREAD

**Issue by ShinKage** [idris-community/idris2-lsp#11]
This is the list of refactoring currently supported by the compiler IDE-Mode that needs to be ported on LSP:

- [x] Case split
- [x] Add clause
- [x] Expression search
- [x] Generate definition
- [x] Make lemma
- [x] Make case
- [x] Make with

The compiler can produce multiple results for expression search and generate definition so a single code action may not be enough.

**Comment by alexhumphreys** [comment]
I'll take "Make case"

**Comment by andorp** [comment]
I'll take GenerateDef

**Comment by ShinKage** [comment]
I'm currently working on "Expression search"
