### ISSUE TITLE
Support Completion Request

### ISSUE THREAD

**Issue by michaelmesser** [idris-community/idris2-lsp#139]
[Completion Request Spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion)

**Comment by DoctorRyner** [comment]
sad no one is picking this up, it is one of the things stopping me from writing much Idris, it's impossible to persuade people to chose this over literally anything with better "editor support"

**Comment by andorp** [comment]
How would you imagine the completion?
Why does the hole driven-development not suitable for your needs?

Would you use it only for record fields, such as `x.fieldY` ?
Would you use it for picking names from all the imported functions in a namespace, such as `fun x y = printLn [|]`?

**Comment by DoctorRyner** [comment]
I don’t understand, does completion have anything to do with hole driven development? Like in any statically typed language, there should be completion for types, functions and record fields

**Comment by andorp** [comment]
I started working on it and will soon have some initial, not that smart version.

**Comment by DoctorRyner** [comment]
Cool! I’ll be looking forward for that

**Comment by DoctorRyner** [comment]
@andorp Hi! Are there any progress?

**Comment by andorp** [comment]
I have a version, but I am not happy with the abstraction; it would render the maintainability terrible, so I am rewriting it in simple terms.
![Screenshot from 2023-03-01 20-55-07](https://user-images.githubusercontent.com/3465327/224032545-60610d9b-3137-4f45-b26c-8941437cbc51.png)

**Comment by andorp** [comment]
Stay tuned, I want to raise the PR this weekend (if time allows)
