### ISSUE TITLE
Factor out LSP library

### ISSUE THREAD

**Issue by michaelmesser** [idris-community/idris2-lsp#142]
This could be useful to allow people to create LSPs for languages written in Idris.

**Comment by ShinKage** [comment]
Would we like to provide a complete server or just the LSP message processing. For the former, we may need to rethink and reorganize some modules (I am not particularly fond of having the handlers in the `Language.LSP` namespace). For the latter, we can already add the `Language.LSP.Message` namespace with all its modules to the ipkg.
