### ISSUE TITLE
Lsp cant find modules defined in other packages

### ISSUE THREAD

**Issue by GunpowderGuy** [idris-community/idris2-lsp#182]
When trying to check functions and data defined in the idris compiler for a custom backend i am working on, I noticed that the vs code plugin cant peek either if they are defined in other packages, so i asked about this in the idris server and after some digging around we found out the lsp i giving this error: 
https://github.com/idris-community/idris2-lsp/blob/0381d6c3dc865937352d5918049234c6e0c1acd6/src/Language/LSP/Definition.idr#L41 
We already confirmed packages are installed with sources on my system, so that should not be the problem

**Comment by locriacyber** [comment]
pack doesn't work, while if you install the packages by "idris2 --install-src x.ipkg", it works

**Comment by locriacyber** [comment]
I fixed this using this script to launch lsp
```
#!/usr/bin/fish

set APPLICATION (/home/user/.pack/bin/pack app-path lsp)

set --path -x IDRIS2_PACKAGE_PATH (/home/user/.pack/bin/pack package-path)
set --path -x IDRIS2_LIBS (/home/user/.pack/bin/pack libs-path)
set --path -x IDRIS2_DATA (/home/user/.pack/bin/pack data-path)
set --path -x IDRIS2_PATH
for dir in $IDRIS2_PACKAGE_PATH
    set --path -xa IDRIS2_PATH $dir/*
end
command $APPLICATION $argv
```

**Comment by GunpowderGuy** [comment]
@locriacyber how do i make vs code launch the lsp in the correct way?

**Comment by locriacyber** [comment]
Make `idris2-lsp` on PATH the script above.
