### ISSUE TITLE
idris2-lsp is stuck and makes the cpu usage 100%

### ISSUE THREAD

**Issue by fonqL** [idris-community/idris2-lsp#191]
System: Ubuntu 2022 on Win10 WSL
idris: Idris 2, version 0.6.0-fd217722b
idris2-lsp:
Idris2 LSP: 0.1.0-a442716c5
Idris2 API: 0.6.0-fd217722
VScode: 1.75.1
idris2-lsp-extension: 0.7.0

test.ipkg:

```
package test
sourcedir = "./"
```

test.idr:

```
record Comp (f,g : Type -> Type) (a : Type) where
  constructor MkComp
  unComp  : f (g a)

Functor f => Functor g =>
Functor (Comp f g)

Foldable f => Foldable g =>
Foldable (Comp f g)

Traversable f => Traversable g =>
Traversable (Comp f g) where
  traverse fn (MkComp val) = map MkComp (traverse {t=f} (traverse{t=g} fn) val)
```

This bug is easily triggered just by opening the file, or moving the cursor on this line (press `->` or `<-` key), or adding some spaces and save, or hovering over the identifier on this line:

```
  traverse fn (MkComp val) = map MkComp (traverse {t=f} (traverse{t=g} fn) val)
```

htop:
```
            |- /bin/sh /home/xxx/.pack/bin/idris2-lsp
            |  └- /bin/sh /home/xxx/.pack/install/fd217722...519b63e4/lsp/a442716c...5623215b/bin/idris2-lsp
(CPU 99.5%) |     └- /usr/bin/chezscheme --program /home/xxx/.pack/instal/fd217722...519b63e4/lsp/a442716c...5623215b/bin/idris2-lsp_app/idris2-lsp.so
```

**Comment by michaelmesser** [comment]
Can you post the Idris LSP server logs? Can this be triggered by running an equivalent command in the Idris REPL?

**Comment by fonqL** [comment]
This is the log when the bug is triggered just by opening the file.
[log.txt](https://github.com/idris-community/idris2-lsp/files/10794335/log.txt)

> running an equivalent command
Sorry but I don't know what it means and what should I do. Is it about `idris2 --ide-mode`?

**Comment by michaelmesser** [comment]
If you run the add clause command with that location in the Idris REPL, what happens?

**Comment by fonqL** [comment]
It is also stuck and cpu usage reaches 100%. Same behavior as above.

**Comment by michaelmesser** [comment]
You should open an issue on the Idris repo since the code causing the issue is there.
