### ISSUE TITLE
"Connection to server got closed" errors

### ISSUE THREAD

**Issue by avalonx** [idris-community/idris2-lsp#49]
API is installed. Using Rodrigo Bamboo's "idris2-lsp" plugin in VSCode.

From VS Code I got the following errors:

Idris 2 LSP Client Output:
[Info - 2:35:54 PM] Connection to server got closed. Server will restart.
[Info - 2:35:54 PM] Connection to server got closed. Server will restart.
[Info - 2:35:55 PM] Connection to server got closed. Server will restart.
[Info - 2:35:55 PM] Connection to server got closed. Server will restart.
[Error - 2:35:56 PM] Connection to server got closed. Server will not be restarted.

idris2-lsp (Extension):
The Idris 2 LSP Client server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by bamboo** [comment]
Any output in the _Idris 2 LSP Server_ output window?

**Comment by michaelmesser** [comment]
Does the server always crash or does it only crash on a certain file?

**Comment by michaelmesser** [comment]
@avalonx Can you provide us with any information?
