### ISSUE TITLE
Go to definition to standard library files

### ISSUE THREAD

**Issue by technic** [idris-community/idris2-lsp#50]
Hi,
Thanks a lot for you work, it works great with the vscode extension.

The main feature, which I am missing now is go to definition for std library things, like `Data.Vect` etc.
As far as I can see now the lsp tries to resolve this external files with respect to the project root directory. This kind of works, if I copy the Data folder from the idris2 source code to my project root. However, It would be nice to have a better solution. 

Regards

**Comment by michaelmesser** [comment]
https://github.com/idris-community/idris2-lsp/pull/42

**Comment by Russoul** [comment]
The functionality has been implemented in #42
Note that you'll need a recent version of the compiler. Just grab the one we have in the submodule, to be safe.
Make sure you install the sources of external dependencies via the new Idris2 CLI command `idris2 --install-with-src your.ipkg, see [idris-lang/idris2#1450](https://github.com/idris-lang/Idris2/pull/1450) for more info.

**Comment by technic** [comment]
Great, it works!

So, when installing idris2 from the sources one need in addition to `make install` run `make install-with-src-libs`

**Comment by ShinKage** [comment]
Yes. I will add a note about it in the README.
