### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by chespinoza** [idris-community/idris2-lsp#57]
Hi, I'm using `Idris 2, version 0.3.0` and when trying to compile I'm getting this error:

![image](https://user-images.githubusercontent.com/3278356/121821956-39b01800-cc94-11eb-9e7c-f043650009ec.png)

Thanks!

**Comment by michaelmesser** [comment]
You must use the commit of Idris 2 specified in the submodule.

**Comment by ShinKage** [comment]
I will add that this is a requirement until Idris2 reaches it's new release, then we will guarantee support also for the new release beside the pinned version in the submodule. Feel free to reopen if there are error with the submodule.
