### ISSUE TITLE
Memory leak/non-termination

### ISSUE THREAD

**Issue by Z-snails** [idris-community/idris2-lsp#73]
The following code causes idris2-lsp to use all my (and other people's) ram, and goes to 100% (of 1 core) cpu usage

https://gist.github.com/Z-snails/38e1b3160d624d52ffcf206aa3f75adf

Changing almost anything fixes it.

**Comment by Z-snails** [comment]
On discord @andorp says
> probably some CodeAction search kicks in, triggering an edge-case in some IDE command which can not be triggered in other IDEs

**Comment by ShinKage** [comment]
It breaks on load or after a code action request?

**Comment by Z-snails** [comment]
Whenever I load the file.

**Comment by andorp** [comment]
I think of code actions because this seems to be fixing the mem/leak:
```
export
rule : Label -> Value -> List Assignment -> Rule
rule l = MkRule l
```

**Comment by ShinKage** [comment]
From my testing it's the semantic highlightning. When disabled, it loads instantly. Also I had other file that caused huge memory spikes with the semantic highlightning on.
I'm currently working on improving logging and adding more logging messages in general, so that we can debug it easier.

**Comment by ShinKage** [comment]
As I suspected it was looping during the processing of semantic tokens. I'm not 100% positive it fixes all the issue with semantic highlightning and strange memory leaks, but at least it solved this issue and another similar case I got. I will still take a better look at the code to find some performance improvements in the future.
