### ISSUE TITLE
getting error when creating my first file

### ISSUE THREAD

**Issue by rambip** [idris-community/idris2-lsp#78]
after installing the idris2 lsp [here](https://github.com/claymager/idris2-pkgs), I used the neovim configuration and tried to get started.

I created an empty test.idr, but when I save it I immediatly get an error: `Error: Source file "/home/rambi/test.idr" is not in the source directory "." `

How do I have to understand this error ?
Is there a project layout I have to follow to be able to use the lsp ?

**Comment by michaelmesser** [comment]
Do you have a `.ipkg`?

**Comment by rambip** [comment]
I didn't have one, and I think I figured out how to use it.
I just wanted to play with the language server, so I used a standalone file.

It would be nice if it were written in the docuentation that you need a .ipkg, and how to do otherwise.

**Comment by ShinKage** [comment]
The first note in the README specifies that a .ipkg is mandatory. I will add a note also in the configuration snippet.

**Comment by rambip** [comment]
Is there a link to the documentation for the .ipkg file ?

It would be nice to have an example foo.ipkg file just to understand the ise of it

**Comment by ShinKage** [comment]
There is a brief introduction in the tutorial https://idris2.readthedocs.io/en/latest/tutorial/packages.html.
And the proper documentation for the format https://idris2.readthedocs.io/en/latest/reference/packages.html.
If you need to quickly and interactively setup an ipkg you can use the command `idris2 --init`.
