### ISSUE TITLE
Errornous files make idris2-lsp output compiler errors to stdout

### ISSUE THREAD

**Issue by loovjo** [idris-community/idris2-lsp#81]
When using idris2-lsp together with [kak-lsp](https://github.com/kak-lsp/kak-lsp), it seemed the connection would randomly break every once in a while, and I had to restart it. After some investigation, it seems if the file being edited contains a compilation error, the error is outputted to stdout and thus sent to the LSP client. I'm guessing the clients that are used to test idris2-lsp will silently ignore this invalid data and thus continue working, but kak-lsp does not, triggering an error (`ERRO Failed to parse header, module: kak_lsp::language_server_transport:74`).

Here's a small example triggering the error: the following file, named `X.idr`, in the project `/tmp/test-project`:

```haskell
main : IO ()
main = do
    putStrLn "Hello"
    return 5 -- Error!
```

Looking at the exact output of the lsp client (`tee`ing the stdout of the server), gives the following: (full file attached below)

```
Content-Length: 1187

{"jsonrpc":"2.0","id":0,"result":{"capabilities"[...]1/1: Building X (/private/tmp/test-project/X.idr)
\x1b[38;5;9;1mError:\x1b[0m \x1b[1mWhile processing right hand side of \x1b[38;5;5;1mmain\x1b[0;1m\x1b[0m. \x1b[1mUndefined name \x1b[38;5;5;1mreturn\x1b[0;1m.\x1b[0m 

\x1b[38;5;12mX:4:5--4:11\x1b[0m
 \x1b[38;5;12m1 |\x1b[0m main : IO ()
 \x1b[38;5;12m2 |\x1b[0m main = do
 \x1b[38;5;12m3 |\x1b[0m     putStrLn "Hello"
 \x1b[38;5;12m4 |\x1b[0m     return 5 -- Error!
         \x1b[38;5;9;1m^^^^^^\x1b[0m

Content-Length: 331

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///private/tmp/test-project/X.idr","version":1,"diagnostics":[{"range":{"start":{"line":3,"character":4},"end":{"line":3,"character":10}},"severity":1,"source":"idris2","message":"While processing right hand side of main. Undefined name return."}]}}
```

The `\x1b`s are the literal escape character, used by the Idris2 compiler to output colors, here's what the file looks like when `cat`ed.

<img width="958" alt="bild" src="https://user-images.githubusercontent.com/8290983/130588812-ed8c6037-dd76-4d67-82af-de96cdbe5304.png">

Conceptually, the solution should be quite simple: disable the compiler output when compiling (or redirect it to stderr). 

[idr.log](https://github.com/idris-community/idris2-lsp/files/7037939/idr.log)

**Comment by ShinKage** [comment]
Thanks for the issue. As mentioned in other issue and in other discussions, we are aware of the issue and we will work on a patch for the compiler.
