### ISSUE TITLE
Getting the following error upon executing `make install`

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [idris-community/idris2-lsp#84]
```
Uncaught error: Can't find package idris2 (any)
```

I have installed idris2 via nix-

```bash
nix-env -i idris2
```

**Comment by andorp** [comment]
The LSP also needs the `idris2` package which refers the compiler API rather than the compiler itself. It is installed via the `make install-api` in non nix-env. Step 8 from the https://github.com/idris-lang/Idris2/blob/main/INSTALL.md
```
### 8: (Optional) Installing the Idris 2 API
```

**Comment by Sinha-Ujjawal** [comment]
I tried installing idris2 using racket bootstrap. It worked, I was able to run `make install-api` as well. Everything seemed to work just fine when I got the following error-

```bash
Exception: attempt to reference unbound identifier fork-thread at line 259, char 6 of $HOME/idris2-lsp/build/exec/idris2-lsp_app/idris2-lsp.ss
```

**Comment by andorp** [comment]
I've never seen that before. Did you install the dedicated `Idris2 @ a7d73d0` version? What is your OS?

**Comment by Sinha-Ujjawal** [comment]
Oh.. I installed idris2 using scheme bootstrap, for that I needed to install [ChezScheme](https://github.com/cisco/ChezScheme/blob/main/BUILDING). I installed it, but it still didn't work for me. :(

Finally, I found this [documentation](https://idris2.readthedocs.io/en/latest/tutorial/starting.html). There they mention that you need to put `--threads` option in `./configure` while installing scheme. This finally worked for me. After this, I was seamlessly able to install everything and I implore the developer to please make this very explicit (for naive users like me) in the installation guide.

**Comment by andorp** [comment]
The Idris community is very open. You may want to include this note in the INSTALL.md or everywhere you see fit. Before opening a PR I would read the https://github.com/idris-lang/Idris2/blob/main/CONTRIBUTING.md guidelines.
