### ISSUE TITLE
Cannot communicate with vscode lsp extension?

### ISSUE THREAD

**Issue by KySpace** [idris-community/idris2-lsp#88]
Showing `Couldn't start client idris 2 LSP Client` and `Starting client failed Launching server using command ~/.idris2/bin/idris2-lsp failed.`.

Is there a way I can test with something other than the extension? 

Environment: vscode on wsl2 debian

**Comment by ShinKage** [comment]
Does `make test` return errors?

**Comment by KySpace** [comment]
@ShinKage test shows successful

**Comment by andorp** [comment]
How did you install it?

**Comment by KySpace** [comment]
@andorp 

I cloned the repo, went to branch `idris2-0.4.0`, and set the embedded `idris2` repo to `v0.4.0` as well. I installed idris2 with `v0.4.0` and the `api` and `lib`. I went back to the `idris2-lsp` repo to install by `make clean` and `make install`. Basically I followed the discord guide [here](https://discord.com/channels/827106007712661524/861617364138721310/863151238749487144) . 

I have also tried with other commits including the most recent ones. Same issue.

**Comment by andorp** [comment]
I assume you installed this VSCode plugin: https://github.com/bamboo/idris2-lsp-vscode.

**Comment by KySpace** [comment]
@andorp Indeed

**Comment by KySpace** [comment]
https://github.com/bamboo/idris2-lsp-vscode/issues/5

I can make it work by modifying the path of `lsp-vscode` extension. It is suggested that 

> In that case it seems the idris2-lsp make install step might be missing something some important files.

**Comment by ShinKage** [comment]
> [bamboo/idris2-lsp-vscode#5](https://github.com/bamboo/idris2-lsp-vscode/issues/5)
> 
> I can make it work by modifying the path of `lsp-vscode` extension. It is suggested that
> 
> > In that case it seems the idris2-lsp make install step might be missing something some important files.

This is very interesting to me, since the install procedure is the same for the LSP server and the compiler. Can you post the difference between the build directory and the install directory?

**Comment by KySpace** [comment]
@ShinKage The install directory is `~/.idris2/bin/idris2-lsp`. 
The build directory is `<idris2-lsp repo>/build/exec/idris2-lsp`

**Comment by ShinKage** [comment]
I was not clear. There are differences between the files and subdirectories inside the install directory and the build directory?

**Comment by KySpace** [comment]
`sdiff` tells that `idris2-lsp.so` differ. The others are the same.

**Comment by andorp** [comment]
I have a script which copies the binary to my `.idris2/bin` , which predates the `make install` , could you try if that works?

```
#!/bin/sh

cp ./build/exec/idris2-lsp ~/.idris2/bin/
cp -r ./build/exec/idris2-lsp_app ~/.idris2/bin/
```

**Comment by KySpace** [comment]
where should I put this? in `Makefile` of the root folder? And I run `make install` again?

**Comment by Russoul** [comment]
Paste it into a new file, without an extension. (e.g. `script`). The file needs to be created in the directory your LSP source resides in.
Then run it in console like this: `./script`. You may need to assign it an executable permission bit prior to running.
This is done like so: `chmod +x ./script`. The console instance has to be rooted in the LSP source folder, obviously.

**Comment by KySpace** [comment]
It does not work after this when I choose the path to be `/.idris2/bin/idris2-lsp`.
I am pretty sure the copying is working since I deleted the original files and they appear again, and I have checked with `sdiff`

**Comment by michaelmesser** [comment]
Is this still an issue?

**Comment by michaelmesser** [comment]
Reopen if this is still an issue

**Comment by KySpace** [comment]
@michaelmesser I think it is fixed now.
